export const PLANS = [
  {
    id: "free",
    plan: "무료",
    price: "0",
    priceNum: 0,
    unit: "원/월",
    desc: "혼자 운영하는 소규모 매장에 적합",
    features: [
      "수익 시뮬레이터 (무제한)",
      "월 3회 AI 브리핑",
      "기본 차트 및 분석",
      "링크 공유",
    ],
    btn: "무료로 시작",
    cls: "pricing-btn-gray",
    href: "/signup",
    popular: false,
  },
  {
    id: "standard",
    plan: "스탠다드",
    price: "9,900",
    priceNum: 9900,
    unit: "원/월",
    desc: "성장하는 매장을 위한 핵심 기능 모음",
    features: [
      "무제한 AI 브리핑",
      "AI 전략 추천 (무제한)",
      "POS 파일 분석",
      "히스토리 12개월",
    ],
    btn: "스탠다드 시작",
    cls: "pricing-btn-blue",
    href: "/pricing",
    popular: true,
  },
  {
    id: "pro",
    plan: "프로",
    price: "29,900",
    priceNum: 29900,
    unit: "원/월",
    desc: "다점포·프랜차이즈 운영자를 위한 플랜",
    features: [
      "스탠다드 모든 기능",
      "히스토리 무제한",
      "팀 멤버 초대 (무제한)",
    ],
    btn: "프로 시작",
    cls: "pricing-btn-gray",
    href: "/pricing",
    popular: false,
  },
];
